"""
api.py

Read-only REST API over the same data the dashboard reads
(triggers.log.jsonl, bets.db), plus a Prometheus-style /metrics
endpoint for scanner health and trigger throughput. This exists as a
second, independent consumer of the app's data, decoupled from the
Streamlit dashboard - nothing here imports dashboard.py, and nothing
in dashboard.py imports this. Either can be extended, replaced, or
pointed at by a different client without touching the other, which is
the actual point: it demonstrates the data layer isn't secretly
coupled to one particular UI.

Run standalone:
    python api.py                          # http://localhost:8000
Or via the dashboard's Scanners tab (registered as "api" in
scanner_manager.py), or directly with uvicorn:
    uvicorn api:app --port 8000

Docs are auto-generated by FastAPI at /docs once running.
"""

from __future__ import annotations

import os
import time

from fastapi import FastAPI
from fastapi.responses import PlainTextResponse

import scanner_manager
import trigger_stats
from clv_engine import BetLogger

app = FastAPI(
    title="Sports Intern API",
    description="Read-only view over trigger detections and CLV performance.",
    version="1.0.0",
)

TRIGGER_LOG_PATH = os.environ.get("TRIGGER_LOG_PATH", "triggers.log.jsonl")
BETS_DB_PATH = os.environ.get("BETS_DB_PATH", "bets.db")

EMPTY_SUMMARY = {
    "total_bets": 0,
    "settled_bets": 0,
    "win_rate": None,
    "avg_odds_taken": None,
    "avg_clv_pct": None,
    "avg_clv_ci95": None,
    "avg_clv_n": 0,
    "net_units": 0.0,
}


@app.get("/health")
def health() -> dict:
    return {"status": "ok", "time": time.time()}


@app.get("/triggers")
def triggers(limit: int = 50) -> list[dict]:
    """Most recent triggers, newest first."""
    rows = trigger_stats.load_trigger_rows(TRIGGER_LOG_PATH)
    rows.sort(key=lambda r: r.get("fired_at", 0), reverse=True)
    return rows[:limit]


@app.get("/triggers/frequency")
def triggers_frequency() -> dict:
    rows = trigger_stats.load_trigger_rows(TRIGGER_LOG_PATH)
    return trigger_stats.frequency_by_rule(rows)


@app.get("/bets/summary")
def bets_summary() -> dict:
    if not os.path.exists(BETS_DB_PATH):
        return EMPTY_SUMMARY
    return BetLogger(db_path=BETS_DB_PATH).summary()


@app.get("/bets/summary-by-rule")
def bets_summary_by_rule() -> dict:
    if not os.path.exists(BETS_DB_PATH):
        return {}
    return BetLogger(db_path=BETS_DB_PATH).summary_by_rule()


@app.get("/metrics", response_class=PlainTextResponse)
def metrics() -> str:
    """Prometheus text-exposition format - scrapeable by a real
    Prometheus instance, or just readable by eye. Deliberately doesn't
    include API-Football quota here: that requires a live network call
    per scrape, which is exactly the kind of budget-multiplying mistake
    task 1 exists to avoid - quota is checked on demand from the
    dashboard's Settings tab instead."""
    lines = ["# TYPE scanner_up gauge", "# TYPE scanner_heartbeat_age_seconds gauge"]
    for name in ("soccer", "basketball", "watchdog"):
        st = scanner_manager.status(name)
        lines.append(f'scanner_up{{name="{name}"}} {1 if st["running"] else 0}')
        age = scanner_manager.heartbeat_age_seconds(name)
        if age is not None:
            lines.append(f'scanner_heartbeat_age_seconds{{name="{name}"}} {age:.1f}')

    lines.append("# TYPE trigger_fired_total counter")
    rows = trigger_stats.load_trigger_rows(TRIGGER_LOG_PATH)
    freq = trigger_stats.frequency_by_rule(rows)
    for rule, stats in freq.items():
        lines.append(f'trigger_fired_total{{rule="{rule}"}} {stats["count"]}')

    if os.path.exists(BETS_DB_PATH):
        summary = BetLogger(db_path=BETS_DB_PATH).summary()
        lines.append("# TYPE bets_total counter")
        lines.append(f"bets_total {summary['total_bets']}")
        if summary["avg_clv_pct"] is not None:
            lines.append("# TYPE avg_clv_pct gauge")
            lines.append(f"avg_clv_pct {summary['avg_clv_pct']:.4f}")

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
